- src/components/borrow/BorrowAnvil.tsx
- src/components/lend/LendAnvil.tsx
- src/components/repay/RepayAnvil.tsx
- src/components/withdraw/WithdrawAnvil.tsx
- src/utils/horizon.ts
* Take into account stellar asset reserves
* Fix HF calculations for 1.02 target
> Max Button Updates

- package-lock.json
- src/components/common/OverlayModal.tsx
- src/components/common/OverlayModalFail.tsx
- src/contexts/wallet.tsx
- src/layouts/DefaultLayout.tsx
- src/pages/supply.tsx
- src/pages/withdraw.tsx
- src/store/blendSlice.ts
> Some fixes

- src/components/backstop/BackstopDepositAnvil.tsx
- src/components/backstop/BackstopQueueAnvil.tsx
- src/components/backstop/BackstopQueueItem.tsx
- src/components/borrow/BorrowAnvil.tsx
- src/components/common/TxOverview.tsx
- src/components/lend/LendAnvil.tsx
- src/components/repay/RepayAnvil.tsx
- src/components/withdraw/WithdrawAnvil.tsx
- src/pages/borrow.tsx
* deploying this to testnet.blend.capital
> feat: add error the majority of input error states to transaction overview

- src/components/backstop/BackstopDepositAnvil.tsx
- src/components/borrow/BorrowAnvil.tsx
- src/components/lend/LendAnvil.tsx
- src/components/repay/RepayAnvil.tsx
- src/components/withdraw/WithdrawAnvil.tsx
> fix: set input amount to 0 after successful transactions

- .eslintrc.json
- src/components/backstop/BackstopMintAnvil.tsx
- src/components/backstop/BackstopQueueItem.tsx
- src/components/backstop/BackstopQueueMod.tsx
- src/layouts/DefaultLayout.tsx
- src/pages/backstop.tsx
Preview deployment available at: https://dev.blend-frontend.pages.dev/
> fix: update backstop withdraw fn and clean up rendering loop

- src/components/markets/MarketsListItem.tsx
- src/pages/borrow.tsx
- src/pages/supply.tsx
- src/utils/token.ts
> add token link

- src/components/backstop/BackstopDepositAnvil.tsx
- src/components/backstop/BackstopMintAnvil.tsx
- src/components/backstop/BackstopQueueAnvil.tsx
- src/components/borrow/BorrowAnvil.tsx
- src/components/lend/LendAnvil.tsx
- src/components/repay/RepayAnvil.tsx
- src/components/withdraw/WithdrawAnvil.tsx
> fix typos on warnings

- src/components/borrow/BorrowMarketCard.tsx
- src/components/borrow/BorrowMarketList.tsx
> hide where lfactor is 0

- src/components/backstop/BackstopQueueAnvil.tsx
> fix q4w expiration date

- src/components/backstop/BackstopDepositAnvil.tsx
- src/components/backstop/BackstopMintAnvil.tsx
- src/components/backstop/BackstopQueueAnvil.tsx
- src/components/borrow/BorrowAnvil.tsx
- src/components/common/AnvilAlert.tsx
- src/components/common/OverlayModal.tsx
- src/components/common/TxOverview.tsx
- src/components/lend/LendAnvil.tsx
- src/components/repay/RepayAnvil.tsx
- src/components/withdraw/WithdrawAnvil.tsx
- src/contexts/wallet.tsx
- src/utils/txSim.tsx
closes #117 
* removed alert and error handling from transaction overview component (not relevant to it) 
* created anvil alert component
* added util function to calculate error based on transaction simulation response 
* implemented new utils on all anvils
* implemented anvil alert component on all anvils
> refactor transaction error handling and remove from component

- src/components/common/TOS.tsx
Thought wallet needed update. ignore name 
JUST TOS
> TOS change/ no wallet

- src/components/common/WalletWarning.tsx
- src/store/blendSlice.ts
- src/store/userSlice.ts
* fix duplicate loading loop due to the fact that multiple components call `loadBlendData` and `loadUserData`
* fix excessive loading when an account does not exist
* fix issues caused by a cyclical function call from `loadBlendData` -> `loadUserData` -> `loadBlendData`. Note - this should likely be refactored in the future but due to plans to implement react query I opted against doing the refactor now
> chore: fix excessive data loading calls

- src/components/backstop/BackstopQueueAnvil.tsx
- src/components/backstop/BackstopQueueItem.tsx
- src/components/backstop/BackstopQueueMod.tsx
fix of https://github.com/blend-capital/blend-ui/issues/139
> toQueueShares added

- package-lock.json
- package.json
- src/components/backstop/BackstopAPR.tsx
- src/components/backstop/BackstopPreviewBar.tsx
- src/components/backstop/BackstopQueueItem.tsx
- src/components/borrow/BorrowMarketList.tsx
- src/components/borrow/BorrowPositionCard.tsx
- src/components/borrow/BorrowPositionList.tsx
- src/components/common/StackedText.tsx
- src/components/common/TooltipText.tsx
- src/components/lend/LendMarketList.tsx
- src/components/lend/LendPositionCard.tsx
- src/components/lend/LendPositionList.tsx
- src/hooks/api.ts
- src/pages/backstop-deposit.tsx
- src/pages/backstop-q4w.tsx
- src/pages/backstop.tsx
- src/pages/borrow.tsx
- src/pages/repay.tsx
- src/pages/supply.tsx
- src/pages/withdraw.tsx
- src/utils/formatter.ts
- src/utils/txSim.tsx
* Update SDK to pull in fix for emissions estimation
* add ledger entry restore functionality for q4w
* add tooltips and cleanup tooltip usage
* patch visual bug in positions table
> Backstop q4w exp

- src/components/auction/OngoingAuctionCard.tsx
- src/components/nav/NavMenu.tsx
- src/pages/auction.tsx
- fix auction scaling to current ledger + 1
> Fix Auction Scaling

- package-lock.json
- package.json
- src/components/bridge/allbridge.tsx
- src/components/nav/NavMenu.tsx
- src/pages/asset.tsx
- src/pages/dashboard.tsx
- src/pages/supply.tsx
- Add allbridge link button to dashboard of pools with usdc, backstop, and menu
> Allbridge button

- src/components/borrow/BorrowPositionCard.tsx
Mobile Repay button fix pathname
> switch repay path

- src/components/auction/BidListItem.tsx
- src/components/auction/FilledAuctionCard.tsx
- src/components/auction/LotListItem.tsx
- src/components/auction/OngoingAuctionCard.tsx
- src/components/auction/OngoingAuctionCardCollapse.tsx
- Implements partial auction fills via user input
- Solves #180
> Partial auction fills

- package.json
- src/utils/auction.ts
- Use correct b token to asset conversion
> Fix auction value calculation

- package-lock.json
- package.json
- src/components/lend/LendAnvil.tsx
- src/components/repay/RepayAnvil.tsx
- src/utils/horizon.ts
- Special case XLM balance errors to inform users of reserve requirements
> Xlm reserve error
